spring:
  application:
    name: checkout-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false #true
        jdbc:
          time_zone: UTC

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: checkout-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual
    producer:
      acks: all
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8082

machine:
  id: 3

razorpay:
  key:
    id: rzp_test_SElR6dCtE9ARWL
    secret: Cm49XI1PUqUYvJevt2QWxq17
  webhook:
    secret: Cm49XI1PUqUYvJevt2QWxq17

logging:
  level:
    org:
      apache:
        http: WARN #DEBUG
        wire: WARN #DEBUG
